import * as Route from '@/constants/routes';
import logo from '@/images/med-logo.png';
import React from 'react';
import { useLocation } from 'react-router-dom';

const HomeGrid = () => {
  return (
    <div id="gw-card-layout" data-grid-breakpoint="ws" data-flow-dir="h" className="a-section a-spacing-none gw-card-layout">
      <div id="desktop-grid-1" data-display-at="smws" data-order-ws="1" className="gw-col celwidget" data-order-sm="1" data-cel-widget="desktop-grid-1">
        <div id="HhLMT6aHR2xLzMGl-gKzeg" className="a-cardui fluid-fat-image-link fluid-card fluid-fat-image-link" data-a-card-type="basic">
          <div className="a-cardui-header">
            <h2 className="a-color-base headline truncate-2line">Beauty picks</h2>
          </div>
          <div className="a-cardui-body">
            <a className="a-link-normal center-image aok-block image-window" href="/b/?node=16225006011">
              <div className="a-section a-spacing-none fluid-image-container">
                <img alt="Beauty picks" src="https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2020/May/Dashboard/Fuji_Dash_Beauty_1x._SY304_CB432774351_.jpg" className="landscape-image" /></div>
            </a>
          </div>
          <div className="a-cardui-footer">
            <a className="a-link-normal see-more truncate-1line" href="/b/?node=16225006011">Shop now</a>
          </div></div>
        {/* <div id="kZnQegNYdeNm6uxRr8ha4g" className="a-cardui fluid-quad-card fluid-card fluid-quad-image-label fluid-quad-image-label" data-a-card-type="basic"><div className="a-cardui-header"><h2 className="a-color-base headline truncate-2line">Gaming accessories</h2></div><div className="a-cardui-body"><div className="a-section a-spacing-small grid-row-1">
          <div className="a-section a-spacing-none quadrant-container quadrant-container-0"><a aria-label="Headsets" className="a-link-normal image-redirect aok-block image-window" href="/s?k=gaming+headsets&amp;ref=nb_sb_noss_2"><div className="a-section a-spacing-none fluid-image-container"><img alt="Headsets" src="https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2021/June/Fuji_Quad_Headset_1x._SY116_CB667159060_.jpg" className="landscape-image" data-a-hires="https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2021/June/Fuji_Quad_Headset_2x._SY232_CB667159060_.jpg" /></div><div className="a-section a-spacing-none image-label aok-inline-block aok-align-center"><span className="a-size-small a-color-base truncate-2line">Headsets</span></div></a></div><div className="a-section a-spacing-none quadrant-container quadrant-container-1"><a aria-label="Keyboards" className="a-link-normal image-redirect aok-block image-window" href="/s?k=gaming+keyboard&amp;ref=nb_sb_noss_1"><div className="a-section a-spacing-none fluid-image-container">
            <img alt="Keyboards" src="https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2021/June/Fuji_Quad_Keyboard_1x._SY116_CB667159063_.jpg" className="landscape-image" data-a-hires="https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2021/June/Fuji_Quad_Keyboard_2x._SY232_CB667159063_.jpg" /></div><div className="a-section a-spacing-none image-label aok-inline-block aok-align-center"><span className="a-size-small a-color-base truncate-2line">Keyboards</span></div></a></div></div><div className="a-section grid-row-2"><div className="a-section a-spacing-none quadrant-container quadrant-container-0"><a aria-label="Computer mice" className="a-link-normal image-redirect aok-block image-window" href="/s?k=gaming+mouse&amp;ref=nb_sb_noss_2"><div className="a-section a-spacing-none fluid-image-container">
              <img alt="Computer mice" src="https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2021/June/Fuji_Quad_Mouse_1x._SY116_CB667159063_.jpg" className="landscape-image" data-a-hires="https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2021/June/Fuji_Quad_Mouse_2x._SY232_CB667159063_.jpg" /></div><div className="a-section a-spacing-none image-label aok-inline-block aok-align-center"><span className="a-size-small a-color-base truncate-2line">Computer mice</span></div></a></div><div className="a-section a-spacing-none quadrant-container quadrant-container-1"><a aria-label="Chairs" className="a-link-normal image-redirect aok-block image-window" href="/s?k=gaming+chairs&amp;ref=nb_sb_noss"><div className="a-section a-spacing-none fluid-image-container">
                <img alt="Chairs" src="https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2021/June/Fuji_Quad_Chair_1x._SY116_CB667159060_.jpg" className="landscape-image" data-a-hires="https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2021/June/Fuji_Quad_Chair_2x._SY232_CB667159060_.jpg" /></div>
                <div className="a-section a-spacing-none image-label aok-inline-block aok-align-center"><span className="a-size-small a-color-base truncate-2line">Chairs</span></div></a></div></div></div><div className="a-cardui-footer"><a className="a-link-normal see-more truncate-1line" href="/b?node=23508887011">See more</a></div></div> */}

      </div>
      <div id="desktop-grid-2" data-order-ws="2" className="gw-col celwidget" data-order-sm="2" data-cel-widget="desktop-grid-2">

        <div id="RdqjdPHR7Al1azIcePLt8Q" className="a-cardui fluid-fat-image-link fluid-card fluid-fat-image-link" data-a-card-type="basic">
          <div className="a-cardui-header">
            <h2 className="a-color-base headline truncate-2line">Easy returns</h2>
          </div>
          <div className="a-cardui-body">
            <a className="a-link-normal center-image aok-block image-window" href="/gp/help/customer/display.html/?nodeId=GXE45NTWZ2QW2ZFM"><div className="a-section a-spacing-none fluid-image-container">
              <img alt="Easy returns" src="https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2020/May/Dashboard/Fuji_Dash_Returns_1x._SY304_CB432774714_.jpg" className="landscape-image" /></div></a>
          </div>
          <div className="a-cardui-footer">
            <a className="a-link-normal see-more truncate-1line" href="/gp/help/customer/display.html/?nodeId=GXE45NTWZ2QW2ZFM">Learn more</a></div></div>

      </div>
      <div id="desktop-grid-3" data-order-ws="3" className="gw-col celwidget" data-order-sm="3" data-cel-widget="desktop-grid-3">
        <div id="KC1cuyLVaRcBNT0ObqwYWA" className="a-cardui fluid-quad-card fluid-card fluid-quad-image-label fluid-quad-image-label" data-a-card-type="basic">
          <div className="a-cardui-header">
            <h2 className="a-color-base headline truncate-2line">Refresh your space</h2>
          </div>
          <div className="a-cardui-body">
            <div className="a-section a-spacing-small grid-row-1">
              <div className="a-section a-spacing-none quadrant-container quadrant-container-0"><a aria-label="Dining" className="a-link-normal image-redirect aok-block image-window" href="/s?k=Dinnerware+%26+accessories&amp;crid=IBML6MYDLJ4A&amp;sprefix=dinnerware+%26+accessorie%2Caps%2C190&amp;ref=nb_sb_noss">
                <div className="a-section a-spacing-none fluid-image-container"><img alt="Dining" src="https://images-na.ssl-images-amazon.com/images/G/01/launchpad/2023/Gateway/January/DesktopQuadCat_186x116_LP-HP_B08MYX5Q2W_01.23._SY116_CB619238939_.jpg" className="landscape-image" /></div><div className="a-section a-spacing-none image-label aok-inline-block aok-align-center"><span className="a-size-small a-color-base truncate-2line">Dining</span></div></a></div><div className="a-section a-spacing-none quadrant-container quadrant-container-1"><a aria-label="Home" className="a-link-normal image-redirect aok-block image-window" href="/s?k=Home&amp;i=kitchen-intl-ship&amp;crid=1QBODY970JKYC&amp;sprefix=home%2Ckitchen-intl-ship%2C164&amp;ref=nb_sb_noss_1"><div className="a-section a-spacing-none fluid-image-container">
                  <img alt="Home" src="https://images-na.ssl-images-amazon.com/images/G/01/launchpad/2023/Gateway/January/DesktopQuadCat_186x116_home_B08RCCP3HV_01.23._SY116_CB619238939_.jpg" className="landscape-image" /></div><div className="a-section a-spacing-none image-label aok-inline-block aok-align-center"><span className="a-size-small a-color-base truncate-2line">Home</span></div></a></div></div><div className="a-section grid-row-2"><div className="a-section a-spacing-none quadrant-container quadrant-container-0"><a aria-label="Kitchen" className="a-link-normal image-redirect aok-block image-window" href="/s?k=Kitchen&amp;i=kitchen-intl-ship&amp;crid=2LRTV3593NEHX&amp;sprefix=kitchen%2Ckitchen-intl-ship%2C202&amp;ref=nb_sb_noss_1"><div className="a-section a-spacing-none fluid-image-container">
                    <img alt="Kitchen" src="https://images-na.ssl-images-amazon.com/images/G/01/launchpad/2023/Gateway/January/DesktopQuadCat_186x116_kitchen_B0126LMDFK_01.23._SY116_CB619238939_.jpg" className="landscape-image" /></div><div className="a-section a-spacing-none image-label aok-inline-block aok-align-center"><span className="a-size-small a-color-base truncate-2line">Kitchen</span></div></a></div><div className="a-section a-spacing-none quadrant-container quadrant-container-1"><a aria-label="Health and Beauty" className="a-link-normal image-redirect aok-block image-window" href="/s?k=health+and+beauty&amp;i=beauty-intl-ship&amp;crid=2036DM6EKNYNA&amp;sprefix=health+and+beauty%2Cbeauty-intl-ship%2C173&amp;ref=nb_sb_noss_2"><div className="a-section a-spacing-none fluid-image-container">
                      <img alt="Health and Beauty" src="https://images-na.ssl-images-amazon.com/images/G/01/launchpad/2023/Gateway/January/DesktopQuadCat_186x116_health-beauty_B07662GN57_01.23._SY116_CB619238939_.jpg" className="landscape-image" /></div>
                      <div className="a-section a-spacing-none image-label aok-inline-block aok-align-center"><span className="a-size-small a-color-base truncate-2line">Health and Beauty</span></div></a></div></div></div><div className="a-cardui-footer"><a className="a-link-normal see-more truncate-1line" href="/gp/goldbox?ref_=nav_cs_gb&amp;deals-widget=%257B%2522version%2522%253A1%252C%2522viewIndex%2522%253A0%252C%2522presetId%2522%253A%2522957D18D8132C0FCBA2EA0F57FEB9A3F8%2522%252C%2522departments%2522%253A%255B%25221055398%2522%255D%252C%2522sorting%2522%253A%2522BY_SCORE%2522%257D">See more</a></div></div>

      </div>
      <hr data-display-at="smws" data-order-sm="4" data-order-ws="5" className="card-flow-row-break" />
      <div id="desktop-grid-4" data-gwi="{&quot;visible&quot;:&quot;desktop-grid-4-visible&quot;,&quot;active&quot;:&quot;desktop-grid-4-active&quot;}" data-display-at="smws" data-order-ws="6" className="gw-col csm-placement-id-5232c45b-5929-4ff0-8eae-5f67afd5c3dc desktop-gateway-atf_36fa66a2-6b4c-4c20-b5ed-6013dc1367eb celwidget pd_rd_wg-dU6K4 pd_rd_w-4xPWR pd_rd_r-1fdc1cc2-285e-499a-a3b8-8d1a27a11edd" data-order-sm="7" data-pf_rd_p="5232c45b-5929-4ff0-8eae-5f67afd5c3dc" data-pd_rd_wg="dU6K4" data-pd_rd_w="4xPWR" data-pd_rd_r="1fdc1cc2-285e-499a-a3b8-8d1a27a11edd" data-ref_="pd_gw_unk" data-csa-op-log-render="" data-csa-c-type="widget" data-csa-c-slot-id="desktop-grid-4" data-csa-c-content-id="5232c45b-5929-4ff0-8eae-5f67afd5c3dc" data-csa-c-id="1s428i-uqootk-l7ohx4-sm803w" data-cel-widget="desktop-grid-4"><div id="_It8ZFVvyU0IMF9iQ7c2xw" className="a-cardui fluid-fat-image-link fluid-card fluid-fat-image-link" data-a-card-type="basic"><div className="a-cardui-header"><h2 className="a-color-base headline truncate-2line">Electronics</h2></div><div className="a-cardui-body"><a className="a-link-normal center-image aok-block image-window" href="/b?node=16225009011"><div className="a-section a-spacing-none fluid-image-container">
        <img alt="Electronics" src="https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2020/May/Dashboard/Fuji_Dash_Electronics_1x._SY304_CB432774322_.jpg" className="landscape-image" data-a-hires="https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2020/May/Dashboard/Fuji_Dash_Electronics_2x._SY608_CB432774322_.jpg" /></div></a></div><div className="a-cardui-footer"><a className="a-link-normal see-more truncate-1line" href="/b?node=16225009011">See more</a></div></div>
      </div>
      <div id="desktop-grid-5" data-gwi="{&quot;visible&quot;:&quot;desktop-grid-5-visible&quot;,&quot;active&quot;:&quot;desktop-grid-5-active&quot;}" data-display-at="smws" data-order-ws="7" className="gw-col csm-placement-id-152091c3-ff04-4c57-8721-f1423f1e428d desktop-gateway-atf_6488ec6e-d0d3-4476-bf67-70bf5711d762 celwidget pd_rd_wg-dU6K4 pd_rd_w-aCigb pd_rd_r-1fdc1cc2-285e-499a-a3b8-8d1a27a11edd" data-order-sm="8" data-pf_rd_p="152091c3-ff04-4c57-8721-f1423f1e428d" data-pd_rd_wg="dU6K4" data-pd_rd_w="aCigb" data-pd_rd_r="1fdc1cc2-285e-499a-a3b8-8d1a27a11edd" data-ref_="pd_gw_unk" data-csa-op-log-render="" data-csa-c-type="widget" data-csa-c-slot-id="desktop-grid-5" data-csa-c-content-id="152091c3-ff04-4c57-8721-f1423f1e428d" data-csa-c-id="3vm1jj-at19cq-bf569y-kq0adm" data-cel-widget="desktop-grid-5"><div id="ARyxZ_hH6lrX3n7fqVgN0g" className="a-cardui fluid-fat-image-link fluid-card fluid-fat-image-link" data-a-card-type="basic"><div className="a-cardui-header"><h2 className="a-color-base headline truncate-2line">Get fit at home</h2></div><div className="a-cardui-body"><a className="a-link-normal center-image aok-block image-window" href="/b?node=16225014011"><div className="a-section a-spacing-none fluid-image-container">
        <img alt="Get fit at home" src="https://images-na.ssl-images-amazon.com/images/G/01/events/GFAH/GWDesktop_SingleImageCard_fitathome_1x._SY304_CB434924743_.jpg" className="landscape-image" data-a-hires="https://images-na.ssl-images-amazon.com/images/G/01/events/GFAH/GWDesktop_SingleImageCard_fitathome_2x._SY608_CB434924743_.jpg" /></div></a></div><div className="a-cardui-footer"><a className="a-link-normal see-more truncate-1line" href="/b?node=16225014011">Explore now</a></div></div>
      </div>
      {/* <div id="desktop-grid-6" data-gwi="{&quot;visible&quot;:&quot;desktop-grid-6-visible&quot;,&quot;active&quot;:&quot;desktop-grid-6-active&quot;}" data-display-at="smws" data-order-ws="8" className="gw-col csm-placement-id-e5b0c85f-569c-4c90-a58f-0c0a260e45a0 desktop-gateway-atf_c5a5ae71-f3c1-4f61-bf7d-323ae610f968 celwidget pd_rd_wg-dU6K4 pd_rd_w-5733m pd_rd_r-1fdc1cc2-285e-499a-a3b8-8d1a27a11edd" data-order-sm="11" data-pf_rd_p="e5b0c85f-569c-4c90-a58f-0c0a260e45a0" data-pd_rd_wg="dU6K4" data-pd_rd_w="5733m" data-pd_rd_r="1fdc1cc2-285e-499a-a3b8-8d1a27a11edd" data-ref_="pd_gw_unk" data-csa-op-log-render="" data-csa-c-type="widget" data-csa-c-slot-id="desktop-grid-6" data-csa-c-content-id="e5b0c85f-569c-4c90-a58f-0c0a260e45a0" data-csa-c-id="ukvf1i-mtfeac-jc8gs3-4xe31v" data-cel-widget="desktop-grid-6">

        <div id="XMtSfDw_63kKiCUBqnoR3w" className="a-cardui quad-label-card card-lite quad-image-label" data-a-card-type="basic"><div className="a-cardui-header"><h2 className="a-color-base headline truncate-1line">Shop by Category</h2></div><div className="a-cardui-body"><div className="a-section grid-row-1"><div className="a-section a-spacing-none quadrant-container-0 aok-float-left"><div className="a-image-container a-dynamic-image-container" style={{height:"85px"}}>
          <img alt="Computers &amp; Accessories" src="https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2019/February/Dashboard/computer120x._SY85_CB468850970_.jpg" data-a-hires="https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2019/February/Dashboard/computer240x._SY170_CB468850970_.jpg" /></div><div className="a-section a-spacing-none a-text-center image-label truncate-2line"><span className="a-size-small a-color-base aok-align-center aok-inline-block">Computers &amp; Accessories</span></div><a aria-label="Computers &amp; Accessories" className="a-link-normal quadrant-overlay" href="/b?node=16225007011"></a></div><div className="a-section a-spacing-none quadrant-container-1 aok-float-left"><div className="a-image-container a-dynamic-image-container" style={{height:"85px"}}>
            <img alt="Video Games" src="https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2019/August/DashboardCard/PS4_120X._SY85_CB438749318_.jpg" data-a-hires="https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2019/August/DashboardCard/PS4_240X._SY170_CB438749318_.jpg" /></div><div className="a-section a-spacing-none a-text-center image-label truncate-2line"><span className="a-size-small a-color-base aok-align-center aok-inline-block">Video Games</span></div><a aria-label="Video Games" className="a-link-normal quadrant-overlay" href="/b?node=16225016011"></a></div></div><div className="a-section a-spacing-mini grid-row-2"><div className="a-section a-spacing-none quadrant-container-0 aok-float-left"><div className="a-image-container a-dynamic-image-container" style={{height:"85px"}}>
              <img alt="Baby" src="https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2019/February/Dashboard/Baby120X._SY85_CB468850882_.jpg" data-a-hires="https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2019/February/Dashboard/Baby240X._SY170_CB468850909_.jpg" /></div><div className="a-section a-spacing-none a-text-center image-label truncate-2line"><span className="a-size-small a-color-base aok-align-center aok-inline-block">Baby</span></div><a aria-label="Baby" className="a-link-normal quadrant-overlay" href="/b?node=16225005011"></a></div><div className="a-section a-spacing-none quadrant-container-1 aok-float-left"><div className="a-image-container a-dynamic-image-container" style={{height:"85px"}}>
                <img alt="Toys &amp; Games" src="https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2019/February/Dashboard/Toys120X._SY85_CB468851693_.jpg" data-a-hires="https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2019/February/Dashboard/Toys240X._SY170_CB468851693_.jpg" /></div><div className="a-section a-spacing-none a-text-center image-label truncate-2line"><span className="a-size-small a-color-base aok-align-center aok-inline-block">Toys &amp; Games</span></div><a aria-label="Toys &amp; Games" className="a-link-normal quadrant-overlay" href="/b?node=16225015011"></a></div></div><p className="a-spacing-top-mini a-size-base description truncate-2line"></p></div><div className="a-cardui-footer"><a className="a-link-normal see-more truncate-1line" href="/b?node=17938598011">Shop now</a></div></div>
      </div> */}
      <div id="desktop-grid-7" data-gwi="{&quot;visible&quot;:&quot;desktop-grid-7-visible&quot;,&quot;active&quot;:&quot;desktop-grid-7-active&quot;}" data-display-at="smws" data-order-ws="9" className="gw-col gw-fixed-col csm-placement-id-eab778f7-37cf-4c6b-9552-5370900592a9 desktop-gateway-atf_4f51e8c8-4b1d-4529-899a-26938d989d21 celwidget pd_rd_wg-dU6K4 pd_rd_w-X64QY pd_rd_r-1fdc1cc2-285e-499a-a3b8-8d1a27a11edd" data-order-sm="12" data-pf_rd_p="eab778f7-37cf-4c6b-9552-5370900592a9" data-pd_rd_wg="dU6K4" data-pd_rd_w="X64QY" data-pd_rd_r="1fdc1cc2-285e-499a-a3b8-8d1a27a11edd" data-ref_="pd_gw_unk" data-csa-op-log-render="" data-csa-c-type="widget" data-csa-c-slot-id="desktop-grid-7" data-csa-c-content-id="eab778f7-37cf-4c6b-9552-5370900592a9" data-csa-c-id="co7fn9-10wakg-4wemww-vnb075" data-cel-widget="desktop-grid-7"><div id="N17FB92Y6ix3hZZDzOLPnA" className="a-cardui fluid-fat-image-link fluid-card fluid-fat-image-link" data-a-card-type="basic"><div className="a-cardui-header"><h2 className="a-color-base headline truncate-2line">Health &amp; Personal Care</h2></div><div className="a-cardui-body"><a className="a-link-normal center-image aok-block image-window" href="/s?i=specialty-aps&amp;bbn=16225006011&amp;rh=n%3A%2116225006011%2Cn%3A3777891&amp;ref=nav_em__nav_desktop_sa_intl_personal_care_0_2_11_9"><div className="a-section a-spacing-none fluid-image-container">
        <img alt="Health &amp; Personal Care" src="https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2022/February/DashboardCards/GW_CONS_AUS_HPC_HPCEssentials_CatCard_Desktop1x._SY304_CB627424361_.jpg" className="landscape-image" data-a-hires="https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2022/February/DashboardCards/GW_CONS_AUS_HPC_HPCEssentials_CatCard_Desktop2x._SY608_CB627424361_.jpg" /></div></a></div><div className="a-cardui-footer"><a className="a-link-normal see-more truncate-1line" href="/s?i=specialty-aps&amp;bbn=16225006011&amp;rh=n%3A%2116225006011%2Cn%3A3777891&amp;ref=nav_em__nav_desktop_sa_intl_personal_care_0_2_11_9">Shop now</a></div></div>
      </div>
      <hr data-display-at="smws" data-order-sm="10" data-order-ws="10" className="card-flow-row-break" data-hide-at-ws="true" />
      {/* <div data-display-at="sm" className="gw-col celwidget" data-order-sm="13" data-csa-op-log-render="" data-csa-c-type="widget" data-csa-c-id="lip5sz-3spdb1-nog4b8-6e9wm7" data-cel-widget=""><div id="HhLMT6aHR2xLzMGl-gKzeg" className="a-cardui fluid-fat-image-link fluid-card fluid-fat-image-link" data-a-card-type="basic">
        <div className="a-cardui-header"><h2 className="a-color-base headline truncate-2line">Beauty picks</h2></div><div className="a-cardui-body"><a className="a-link-normal center-image aok-block image-window" href="/b/?node=16225006011"><div className="a-section a-spacing-none fluid-image-container">
        <img alt="Beauty picks" src="https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2020/May/Dashboard/Fuji_Dash_Beauty_1x._SY304_CB432774351_.jpg" className="landscape-image" data-a-hires="https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2020/May/Dashboard/Fuji_Dash_Beauty_2x._SY608_CB432774344_.jpg" /></div></a></div><div className="a-cardui-footer"><a className="a-link-normal see-more truncate-1line" href="/b/?node=16225006011">Shop now</a></div></div>
      </div> */}

    </div>
  )
}


export default HomeGrid;